#!/bin/bash
source "$PATH_DEV"/env.sh
export PATH_CE="$PATH_WIN/Cheat Engine 7.5"
export PATH_DBG="$PATH_WIN/Debugger"
alias ce="\"$PATH_CE\"/Cheat Engine.exe &"
alias dbg32="\"$PATH_DBG\"/release/x32/x32dbg.exe &"
alias dbg64="\"$PATH_DBG\"/release/x64/x64dbg.exe &"
echo "HACK ENV SETUP *******************************************"
echo "CHEAT ENGINE      : $PATH_CE								"
echo "DEBUGGER          : $PATH_DBG								"
echo "**********************************************************"
echo "HOTKEYS **************************************************"
echo "ce                : run Cheat Engine 7.5"
echo "dbg32             : run x32 debugger"
echo "dbg64             : run x64 debugger"
echo "**********************************************************"
